### ISSUE TITLE
Breaks location for certain countries

### ISSUE THREAD

**Issue by ghosty141** [StephanMc/extension-restore-google-maps#2]
Your addon makes google search think the user is from switzerland. This is pretty annoying for german users (like) me for example. The addon must not do any location changes! This really messes with the search results.

**Comment by StephanMc** [comment]
Hi

Thank you for your feedback regarding the extension.  I completely understand that adjusting the location to simulate being from Switzerland could disrupt your search results, especially if you are using Google from Germany.

To restore the Maps button in Google Search, we actually had two options: directly modify the HTML code of the Google page, or simulate a different location (any country outside the European Union).  

Each of these methods has its advantages and disadvantages.

The first option, editing the HTML, can be very sensitive to Google updates.  Which could make the extension obsolete with each update from them.

The second option, with localization, allows the extension to work more stable and predictable since we are using Google's native features.  That said, I recognize that this may induce search results specific to Switzerland, which is not ideal for all users.

Your experience is very important to hear, and I am more than willing to explore ways to minimize the specific inconveniences you experience.

For example, in the latest commit, I was able to adjust interactions with Google Flights to avoid unwanted price changes in CHF, so that it stays in Euro.  I would be happy to receive more details on the problems you encountered in order to find a suitable solution.

Once again, thank you for your feedback, and I hope we can improve your experience with the extension.

Best,
Stephane

**Comment by StephanMc** [comment]
Just as an information, the extension got updated to use Andorre as location of search results, instead of Switzerland now. This changes should improve more results, since Andorre uses Euros currency instead of CHF like it was with Switzerland. 

Andorre is a small country between France and Spain, so most of addresses lookup should more target your actual internet connection location than the small country's. Anyway, if there is an issue, please let me know.
The change will be visible in version 1.0.5+ 

Best,
Stéphane

**Comment by drownzz** [comment]
My search results have been affected aswell, and I'm now getting a lot of results from Belgium instead of the Netherlands.

**Comment by StephanMc** [comment]
> My search results have been affected aswell, and I'm now getting a lot of results from Belgium instead of the Netherlands.

Yeah I can understand, sorry for that. As explained above, thats the drawback when similar locations would exists between Andorra and your actual location. 

As a workaround, I can only suggest to add the country or city among your keywords, the idea would be to more specifically target your actual location in order to help with Maps feature, in case of conflicts.
