### ISSUE TITLE
Why does extension need my browsing history?

### ISSUE THREAD

**Issue by whatupman1** [StephanMc/extension-restore-google-maps#3]
When adding the extension Google informs me the extension will read and edit my data on google.com (which is fine, and needed) but also read my browsing history. Why does extension need my browsing history?

**Comment by StephanMc** [comment]
Hey. Sorry for the late reply. 

> but also read my browsing history. Why does extension need my browsing history?

The extension actually does not read any browser history, it is even not in need to do so. 

The confusion comes where it needs to edit the user google's url to allow showing the maps feature, and it is that the API allowing developers to edit users url is the same which also allow to read browser history (because history is related to urls). Hence this message you received from Google. 

While I understand the confusion, it is actually not something the extension needs in order to work.
